module.exports = {
  apps: [
    {
      name: 'app',
      script: './app.js',
      watch: true,
      instances: 1,
      exec_mode: 'fork',
      ignore_watch: [
        'node_modules',
        'logs',
        '*.log',
        'temp',
        '*.tmp',
        '*.bak',
        'test',
        'public',
        '.cache',
        '*.md',
        'docs',
        'dist',
        'build',
        '.vscode',
        '.idea',
        '*.sublime-*',
        'uploads',
        'data',
        '*.csv',
        '*.json',
        'integration_tests',
        'unit_tests',
        '*.error',
        'log_files',
      ],
      watch_options: {
        followSymlinks: false,
      },
      env: {
        NODE_ENV: 'development',
      },
      env_production: {
        NODE_ENV: 'production',
      },
      max_memory_restart: '300M',
      autorestart: true,
      cron_restart: '0 3 * * *',
      merge_logs: true,
    },
  ],
};
